option(
    'pid-file',
    type: 'string',
    description: 'Path to PID file (usually ${RUN_DIR}/plymouth-openrc-plugin.pid)',
    value: '/run/plymouth/plymouth-openrc-plugin.pid',
)
option(
    'run-dir',
    type: 'string',
    description: 'Run directory',
    value: '/run/plymouth',
)
option(
    'plymouth-binary',
    type: 'string',
    description: 'Path to plymouth binary',
    value: '/bin/plymouth',
)
option(
    'plymouthd-binary',
    type: 'string',
    description: 'Path to plymouthd daemon binary',
    value: '/sbin/plymouthd',
)
